version: "3.9"

services:

  ###########################
  # Backend
  ###########################

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: pingme-backend

    ports:
      - "4000:4000"

    env_file:
      - ./backend/.env

    restart: unless-stopped

    volumes:
      - ./logs:/app/logs

    networks:
      - pingme-network


  ###########################
  # Frontend
  ###########################

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev

    container_name: pingme-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - pingme-network


  ###########################
  # Loki
  ###########################

  loki:
    image: grafana/loki:3.5.2

    container_name: loki

    ports:
      - "3100:3100"

    command: -config.file=/etc/loki/loki-config.yml

    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/loki

    restart: unless-stopped

    networks:
      - pingme-network


  ###########################
  # Promtail
  ###########################

  promtail:
    image: grafana/promtail:3.5.2

    container_name: promtail

    ports:
      - "9080:9080"

    command: -config.file=/etc/promtail/promtail-config.yml

    volumes:
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./logs:/logs

    depends_on:
      - loki

    restart: unless-stopped

    networks:
      - pingme-network


  ###########################
  # Prometheus
  ###########################

  prometheus:
    image: prom/prometheus:latest

    container_name: prometheus

    ports:
      - "9090:9090"

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - pingme-network


  ###########################
  # Grafana
  ###########################

  grafana:
    image: grafana/grafana:latest

    container_name: grafana

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - grafana-data:/var/lib/grafana

    depends_on:
      - prometheus
      - loki

    restart: unless-stopped

    networks:
      - pingme-network


networks:
  pingme-network:


volumes:
  loki-data:
  grafana-data: